import { describe, it, expect } from 'vitest';
import { PdfReportRenderer } from '../pdf-renderer.js';

describe('PdfReportRenderer', () => {
  const renderer = new PdfReportRenderer();

  it('renders empty markdown to a valid PDF buffer', async () => {
    const buf = await renderer.render('');
    expect(buf).toBeInstanceOf(Buffer);
    expect(buf.length).toBeGreaterThan(0);
    expect(buf.subarray(0, 5).toString()).toBe('%PDF-');
  });

  it('renders a heading to a valid PDF', async () => {
    const buf = await renderer.render('# Hello World');
    expect(buf.subarray(0, 5).toString()).toBe('%PDF-');
    expect(buf.length).toBeGreaterThan(100);
  });

  it('renders paragraphs with bold and italic', async () => {
    const md = '**Bold text** and *italic text* and normal text.';
    const buf = await renderer.render(md);
    expect(buf.subarray(0, 5).toString()).toBe('%PDF-');
    expect(buf.length).toBeGreaterThan(100);
  });

  it('renders a table to a valid PDF', async () => {
    const md = '| Name | Value |\n| --- | --- |\n| A | 1 |\n| B | 2 |';
    const buf = await renderer.render(md);
    expect(buf.subarray(0, 5).toString()).toBe('%PDF-');
    expect(buf.length).toBeGreaterThan(100);
  });

  it('renders a list to a valid PDF', async () => {
    const md = '- First item\n- Second item\n- Third item';
    const buf = await renderer.render(md);
    expect(buf.subarray(0, 5).toString()).toBe('%PDF-');
    expect(buf.length).toBeGreaterThan(100);
  });

  it('renders horizontal rules', async () => {
    const md = 'Before\n\n---\n\nAfter';
    const buf = await renderer.render(md);
    expect(buf.subarray(0, 5).toString()).toBe('%PDF-');
  });

  it('renders a full workspace report markdown', async () => {
    const md = [
      '# Workspace Report',
      '',
      '**Theme:** Healthcare Analytics',
      '**Key Topics:** clinical trials, patient outcomes',
      '',
      '## Source Overview',
      '',
      '| Type | Count |',
      '| --- | --- |',
      '| markdown | 3 |',
      '| csv | 2 |',
      '',
      '## Important Sources',
      '',
      '### report.md',
      '- **Kind:** document | **Relevance:** 95%',
      '- Critical clinical trial report',
      '',
      '## Suggested Questions',
      '',
      '- What is this workspace about?',
      '- How are the sources related?',
      '',
      '---',
      '*Report generated by ContextOS on 2026-05-12 08:00:00*',
    ].join('\n');

    const buf = await renderer.render(md);
    expect(buf.subarray(0, 5).toString()).toBe('%PDF-');
    // A full report should produce a reasonably sized PDF
    expect(buf.length).toBeGreaterThan(500);
  });
});
