import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { WorkspaceReportGenerator } from '../report-generator.js';

describe('WorkspaceReportGenerator', () => {
  const base = resolve(tmpdir(), `contextos-report-test-${Date.now()}`);
  const outputDir = resolve(base, 'output');
  const sourcesDir = resolve(base, 'sources');

  beforeEach(() => {
    mkdirSync(outputDir, { recursive: true });
    mkdirSync(sourcesDir, { recursive: true });
  });

  afterEach(() => {
    rmSync(base, { recursive: true, force: true });
  });

  it('generates a report with a header even when no artifacts exist', () => {
    const gen = new WorkspaceReportGenerator(outputDir, sourcesDir);
    const md = gen.generate();
    expect(md).toContain('# Workspace Report');
    expect(md).toContain('Report generated by ContextOS');
  });

  it('includes overview section with theme and key topics', () => {
    writeFileSync(
      resolve(outputDir, 'workspace-context.json'),
      JSON.stringify({
        primaryTheme: 'Healthcare Analytics',
        keyTopics: ['patient outcomes', 'clinical trials'],
        keyEntities: ['Hospital A'],
        detectedCapabilities: { hasDocuments: true },
      }),
    );

    const gen = new WorkspaceReportGenerator(outputDir, sourcesDir);
    const md = gen.generate();
    expect(md).toContain('**Theme:** Healthcare Analytics');
    expect(md).toContain('patient outcomes');
    expect(md).toContain('Hospital A');
  });

  it('includes important sources sorted by relevance', () => {
    writeFileSync(
      resolve(outputDir, 'source-profiles.json'),
      JSON.stringify([
        { fileName: 'low.txt', sourceKind: 'note', relevanceScore: 0.3, summary: 'minor', fileType: 'txt', detectedTopics: [] },
        { fileName: 'high.md', sourceKind: 'spec', relevanceScore: 0.95, summary: 'critical spec', fileType: 'md', detectedTopics: ['api'] },
        { fileName: 'mid.csv', sourceKind: 'data', relevanceScore: 0.8, summary: 'data file', fileType: 'csv', detectedTopics: [] },
      ]),
    );

    const gen = new WorkspaceReportGenerator(outputDir, sourcesDir);
    const md = gen.generate();

    expect(md).toContain('## Important Sources');
    expect(md).toContain('### high.md');
    expect(md).toContain('### mid.csv');
    // low.txt (relevance 0.3) should NOT appear in important sources
    expect(md).not.toContain('### low.txt');

    // high.md should appear before mid.csv (sorted by relevance)
    const highIdx = md.indexOf('### high.md');
    const midIdx = md.indexOf('### mid.csv');
    expect(highIdx).toBeLessThan(midIdx);
  });

  it('includes relationships table when present', () => {
    writeFileSync(
      resolve(outputDir, 'workspace-relationships.json'),
      JSON.stringify({
        workspaceId: 'ws1',
        generatedAt: '2024-01-01',
        relationships: [
          {
            sourceA: 'api.md',
            sourceB: 'schema.json',
            type: 'data_dependency',
            confidence: 0.9,
            evidence: ['shared entity: User'],
          },
        ],
      }),
    );

    const gen = new WorkspaceReportGenerator(outputDir, sourcesDir);
    const md = gen.generate();
    expect(md).toContain('## Source Relationships');
    expect(md).toContain('api.md');
    expect(md).toContain('schema.json');
    expect(md).toContain('data_dependency');
    expect(md).toContain('90%');
  });

  it('includes irrelevant sources section', () => {
    writeFileSync(
      resolve(outputDir, 'workspace-context.json'),
      JSON.stringify({
        primaryTheme: 'Test',
        irrelevantSources: [
          { fileName: 'junk.txt', reason: 'Not related to workspace theme' },
        ],
        detectedCapabilities: {},
      }),
    );

    const gen = new WorkspaceReportGenerator(outputDir, sourcesDir);
    const md = gen.generate();
    expect(md).toContain('Irrelevant');
    expect(md).toContain('junk.txt');
  });

  it('includes source references table from profiles', () => {
    writeFileSync(
      resolve(outputDir, 'source-profiles.json'),
      JSON.stringify([
        { fileName: 'data.csv', fileType: 'csv', sourceKind: 'data', relevanceScore: 0.5, summary: '', detectedTopics: [] },
      ]),
    );

    const gen = new WorkspaceReportGenerator(outputDir, sourcesDir);
    const md = gen.generate();
    expect(md).toContain('## Source References');
    expect(md).toContain('data.csv');
    expect(md).toContain('50%');
  });

  it('falls back to filesystem listing when no profiles exist', () => {
    writeFileSync(resolve(sourcesDir, 'readme.md'), '# Hello');
    writeFileSync(resolve(sourcesDir, 'data.csv'), 'a,b\n1,2');

    const gen = new WorkspaceReportGenerator(outputDir, sourcesDir);
    const md = gen.generate();
    expect(md).toContain('## Source References');
    expect(md).toContain('readme.md');
    expect(md).toContain('data.csv');
  });

  it('includes suggested questions section', () => {
    writeFileSync(
      resolve(outputDir, 'workspace-context.json'),
      JSON.stringify({
        primaryTheme: 'Test',
        detectedCapabilities: { hasDocuments: true, canCalculate: true },
      }),
    );

    const gen = new WorkspaceReportGenerator(outputDir, sourcesDir);
    const md = gen.generate();
    expect(md).toContain('## Suggested Questions');
    expect(md).toContain('What is this workspace about?');
    expect(md).toContain('What calculations can I run?');
  });

  it('includes workbook section when workbook profile exists', () => {
    writeFileSync(
      resolve(outputDir, 'workbook-profile.json'),
      JSON.stringify({
        sheets: [{ name: 'Sheet1' }, { name: 'Results' }],
        candidateMetrics: ['yield', 'weight'],
      }),
    );
    writeFileSync(
      resolve(outputDir, 'normalized-observations.json'),
      JSON.stringify([
        { metric: 'yield', value: 10 },
        { metric: 'weight', value: 5 },
      ]),
    );

    const gen = new WorkspaceReportGenerator(outputDir, sourcesDir);
    const md = gen.generate();
    expect(md).toContain('## Workbook');
    expect(md).toContain('Sheet1');
    expect(md).toContain('Results');
    expect(md).toContain('yield');
    expect(md).toContain('2'); // 2 observations
  });

  it('includes workspace summary quality issues', () => {
    writeFileSync(
      resolve(outputDir, 'workspace-summary.json'),
      JSON.stringify({
        totalSources: 5,
        sourcesByType: { md: 3, csv: 2 },
        duplicateSources: 1,
        outdatedSources: 0,
        conflictingSources: 2,
      }),
    );

    const gen = new WorkspaceReportGenerator(outputDir, sourcesDir);
    const md = gen.generate();
    expect(md).toContain('| md | 3 |');
    expect(md).toContain('1 duplicate');
    expect(md).toContain('2 conflicting');
  });
});
