import { readdirSync, statSync, existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { LocalRetriever } from './local-retriever.js';
import type {
  WorkspaceContext,
  SourceProfile,
  SourceRelationshipMap,
  WorkspaceSummary,
} from '@contextos/types';

/**
 * Generates a Markdown workspace report from analysis artifacts.
 * Fully deterministic — no LLM calls.
 */
export class WorkspaceReportGenerator {
  private readonly retriever: LocalRetriever;

  constructor(
    private readonly outputDir: string,
    private readonly sourcesDir: string,
  ) {
    this.retriever = new LocalRetriever(outputDir, sourcesDir);
  }

  generate(): string {
    const ctx = this.retriever.loadWorkspaceContext();
    const profiles = this.retriever.loadSourceProfiles();
    const relMap = this.retriever.loadWorkspaceRelationships();
    const wbProfile = this.retriever.loadWorkbookProfile();
    const observations = this.retriever.loadNormalizedObservations();
    const summary = this.loadWorkspaceSummary();

    const sections: string[] = [
      this.overviewSection(ctx, summary, profiles),
      this.importantSourcesSection(profiles),
      this.irrelevantSection(ctx, relMap),
      this.relationshipsSection(relMap),
      this.workbookSection(wbProfile, observations),
      this.calculationsSection(observations),
      this.suggestedQuestionsSection(ctx),
      this.sourceReferencesSection(profiles),
    ];

    const body = sections.filter(s => s.length > 0).join('\n\n');
    const timestamp = new Date().toISOString().replace('T', ' ').slice(0, 19);
    return `${body}\n\n---\n*Report generated by ContextOS on ${timestamp}*\n`;
  }

  // ── Sections ─────────────────────────────────────────────────────

  private overviewSection(
    ctx: WorkspaceContext | null,
    summary: WorkspaceSummary | null,
    profiles: SourceProfile[] | null,
  ): string {
    const lines: string[] = ['# Workspace Report'];

    const theme = ctx?.primaryTheme ?? 'Unknown';
    lines.push('', `**Theme:** ${theme}`);

    if (ctx?.keyTopics && ctx.keyTopics.length > 0) {
      lines.push(`**Key Topics:** ${ctx.keyTopics.join(', ')}`);
    }
    if (ctx?.keyEntities && ctx.keyEntities.length > 0) {
      lines.push(`**Key Entities:** ${ctx.keyEntities.join(', ')}`);
    }

    // Source counts
    const totalSources = summary?.totalSources ?? profiles?.length ?? 0;
    lines.push('', '## Source Overview', '');

    if (summary?.sourcesByType && Object.keys(summary.sourcesByType).length > 0) {
      lines.push(`| Type | Count |`, `| --- | --- |`);
      for (const [type, count] of Object.entries(summary.sourcesByType)) {
        lines.push(`| ${type} | ${count} |`);
      }
    } else {
      lines.push(`Total sources: ${totalSources}`);
    }

    if (summary) {
      const qualityItems: string[] = [];
      if (summary.duplicateSources > 0) qualityItems.push(`${summary.duplicateSources} duplicate(s)`);
      if (summary.outdatedSources > 0) qualityItems.push(`${summary.outdatedSources} outdated`);
      if (summary.conflictingSources > 0) qualityItems.push(`${summary.conflictingSources} conflicting`);
      if (qualityItems.length > 0) {
        lines.push('', `**Quality issues:** ${qualityItems.join(', ')}`);
      }
    }

    return lines.join('\n');
  }

  private importantSourcesSection(profiles: SourceProfile[] | null): string {
    if (!profiles || profiles.length === 0) return '';

    const important = profiles
      .filter(p => p.relevanceScore >= 0.7)
      .sort((a, b) => b.relevanceScore - a.relevanceScore);

    if (important.length === 0) return '';

    const lines: string[] = ['## Important Sources', ''];
    for (const p of important) {
      lines.push(`### ${p.fileName}`);
      lines.push(`- **Kind:** ${p.sourceKind} | **Relevance:** ${(p.relevanceScore * 100).toFixed(0)}%`);
      if (p.summary) lines.push(`- ${p.summary}`);
      if (p.detectedTopics.length > 0) {
        lines.push(`- **Topics:** ${p.detectedTopics.join(', ')}`);
      }
      lines.push('');
    }

    return lines.join('\n').trimEnd();
  }

  private irrelevantSection(
    ctx: WorkspaceContext | null,
    relMap: SourceRelationshipMap | null,
  ): string {
    const irrelevant = ctx?.irrelevantSources ?? [];
    const isolated = relMap?.relationships.filter(r => r.type === 'isolated_source') ?? [];

    if (irrelevant.length === 0 && isolated.length === 0) return '';

    const lines: string[] = ['## Irrelevant & Isolated Sources', ''];

    if (irrelevant.length > 0) {
      lines.push('**Flagged as irrelevant:**', '');
      for (const s of irrelevant) {
        lines.push(`- **${s.fileName}** — ${s.reason}`);
      }
    }

    if (isolated.length > 0) {
      if (irrelevant.length > 0) lines.push('');
      lines.push('**Isolated sources** (no cross-file relationships detected):', '');
      for (const r of isolated) {
        const reason = r.evidence.length > 0 ? ` — ${r.evidence[0]}` : '';
        lines.push(`- ${r.sourceA}${reason}`);
      }
    }

    return lines.join('\n').trimEnd();
  }

  private relationshipsSection(relMap: SourceRelationshipMap | null): string {
    if (!relMap) return '';

    const connected = relMap.relationships
      .filter(r => r.type !== 'isolated_source')
      .sort((a, b) => b.confidence - a.confidence);

    if (connected.length === 0) return '';

    const lines: string[] = [
      '## Source Relationships',
      '',
      '| Source A | Source B | Type | Confidence | Evidence |',
      '| --- | --- | --- | --- | --- |',
    ];

    for (const r of connected) {
      const conf = `${(r.confidence * 100).toFixed(0)}%`;
      const evidence = r.evidence.join('; ');
      lines.push(`| ${r.sourceA} | ${r.sourceB} | ${r.type} | ${conf} | ${evidence} |`);
    }

    return lines.join('\n');
  }

  private workbookSection(
    wbProfile: Record<string, unknown> | null,
    observations: Array<Record<string, unknown>> | null,
  ): string {
    if (!wbProfile) return '';

    const lines: string[] = ['## Workbook & Table Insights', ''];

    // Sheet names
    const sheets = wbProfile['sheets'] as Array<Record<string, unknown>> | undefined;
    if (Array.isArray(sheets) && sheets.length > 0) {
      const names = sheets
        .map(s => (s['name'] ?? s['sheetName']) as string)
        .filter(Boolean);
      if (names.length > 0) {
        lines.push(`**Sheets:** ${names.join(', ')}`, '');
      }
    }

    // Metrics
    const metrics = wbProfile['candidateMetrics'] as string[] | undefined;
    if (Array.isArray(metrics) && metrics.length > 0) {
      lines.push(`**Available metrics:** ${metrics.join(', ')}`, '');
    }

    // Observation count
    if (observations && observations.length > 0) {
      lines.push(`**Normalized observations:** ${observations.length}`);
    }

    return lines.join('\n').trimEnd();
  }

  private calculationsSection(
    observations: Array<Record<string, unknown>> | null,
  ): string {
    if (!observations || observations.length === 0) return '';

    const metrics = [...new Set(observations.map(o => o['metric'] as string).filter(Boolean))].sort();
    if (metrics.length === 0) return '';

    const groupFields = ['section', 'treatment', 'plantPart', 'variety'] as const;
    const availableGroups: string[] = [];
    for (const field of groupFields) {
      const values = new Set(observations.map(o => o[field] as string).filter(Boolean));
      if (values.size > 1) availableGroups.push(field);
    }

    const lines: string[] = [
      '## Available Calculations',
      '',
      `**Metrics:** ${metrics.join(', ')}`,
      '',
      '**Supported operations:** count, sum, average, min, max, median',
    ];

    if (availableGroups.length > 0) {
      lines.push(`**Group-by fields:** ${availableGroups.join(', ')}`);
    }

    return lines.join('\n');
  }

  private suggestedQuestionsSection(ctx: WorkspaceContext | null): string {
    const questions: string[] = [];

    // Always suggest overview
    questions.push('What is this workspace about?');

    if (ctx?.detectedCapabilities) {
      const cap = ctx.detectedCapabilities;
      if (cap.hasDocuments) {
        questions.push('What are the most important documents?');
      }
      if (cap.hasWorkbooks) {
        questions.push('What sheets are in the workbook?');
      }
      if (cap.canCalculate) {
        questions.push('What calculations can I run?');
      }
      if (cap.hasIrrelevantSources) {
        questions.push('Which files are irrelevant?');
      }
    }

    questions.push('How are the sources related?');

    const lines: string[] = [
      '## Suggested Questions',
      '',
      'You can ask these questions in the Q&A panel:',
      '',
    ];
    for (const q of questions) {
      lines.push(`- ${q}`);
    }

    return lines.join('\n');
  }

  private sourceReferencesSection(profiles: SourceProfile[] | null): string {
    // Try to get file info from source profiles first
    if (profiles && profiles.length > 0) {
      const lines: string[] = [
        '## Source References',
        '',
        '| File | Type | Kind | Relevance |',
        '| --- | --- | --- | --- |',
      ];
      for (const p of profiles) {
        const rel = `${(p.relevanceScore * 100).toFixed(0)}%`;
        lines.push(`| ${p.fileName} | ${p.fileType} | ${p.sourceKind} | ${rel} |`);
      }
      return lines.join('\n');
    }

    // Fallback: list files from sourcesDir
    try {
      const files = readdirSync(this.sourcesDir).filter(f => !f.startsWith('.'));
      if (files.length === 0) return '';

      const lines: string[] = [
        '## Source References',
        '',
        '| File | Size |',
        '| --- | --- |',
      ];
      for (const f of files) {
        try {
          const stat = statSync(resolve(this.sourcesDir, f));
          const sizeKB = (stat.size / 1024).toFixed(1);
          lines.push(`| ${f} | ${sizeKB} KB |`);
        } catch {
          lines.push(`| ${f} | — |`);
        }
      }
      return lines.join('\n');
    } catch {
      return '';
    }
  }

  // ── Helpers ──────────────────────────────────────────────────────

  private loadWorkspaceSummary(): WorkspaceSummary | null {
    const filePath = resolve(this.outputDir, 'workspace-summary.json');
    if (!existsSync(filePath)) return null;
    try {
      return JSON.parse(readFileSync(filePath, 'utf-8')) as WorkspaceSummary;
    } catch {
      return null;
    }
  }
}
